const CONTAINER_SELECTOR = '.js-chart__impressions';

const DISAPPOINT_START_COLOR = '#909090';
const DISAPPOINT_END_COLOR = '#3D4975';

const SATISFACTORY_START_COLOR = '#BC9CFF';
const SATISFACTORY_END_COLOR = '#8BA4F9';

const GOOD_START_COLOR = '#6FCF97';
const GOOD_END_COLOR = '#66D2EA';

const GREAT_START_COLOR = '#FFE39C';
const GREAT_END_COLOR = '#FFBA9C';

export {
  CONTAINER_SELECTOR,
  DISAPPOINT_END_COLOR,
  DISAPPOINT_START_COLOR,
  SATISFACTORY_END_COLOR,
  SATISFACTORY_START_COLOR,
  GOOD_END_COLOR,
  GOOD_START_COLOR,
  GREAT_END_COLOR,
  GREAT_START_COLOR,
};
