import '../views/components/dropdown/dropdown'
import '../views/components/masked-text-field/masked-text-field'
import '../views/components/filter-date/filter-date'
import '../views/components/range-slider/range-slider'
import '../views/components/pagination/pagination'
import '../views/components/expand-list/expand-list'
import '../views/components/preview-room/preview-room'

import '../views/components/logo/images/logo.png'
import '../views/components/review-list/images/review-image1.svg'
import '../views/components/review-list/images/review-image2.svg'
import '../views/components/review-list/images/review-image3.svg'
import '../views/components/preview-room/images/preview-room1.png'
import '../views/components/preview-room/images/preview-room2.png'
import '../views/components/preview-room/images/preview-room3.png'

import '../views/components/pagination/images/pagination-arrow.svg'
import '../views/components/feedback/images/avatar.svg'

import '../views/components/card/booking-card/images/services.svg'
