//components files
import '../views/components/dropdown/dropdown';
import '../views/components/masked-text-field/masked-text-field';
import '../views/components/filter-date/filter-date';
import '../views/components/chart/chart';
import '../views/components/expand-list/expand-list';
import '../views/components/preview-room/preview-room';
import '../views/components/header/header';
import '../views/components/datepicker/datepicker';
import '../views/components/range-date/range-date';
import '../views/components/filter-date/filter-date';
import '../views/components/range-slider/range-slider';
import '../views/components/pagination/pagination';

//pages files
import '../views/pages/search-room/search-room';

//components images
import '../views/components/logo/images/logo.png';
import '../views/components/review-list/images/review-image1.svg';
import '../views/components/review-list/images/review-image2.svg';
import '../views/components/review-list/images/review-image3.svg';
import '../views/components/preview-room/images/preview-room1.png';
import '../views/components/preview-room/images/preview-room2.png';
import '../views/components/preview-room/images/preview-room3.png';
import '../views/components/pagination/images/pagination-arrow.svg';
import '../views/components/feedback/images/avatar.svg';
import '../views/components/feedback/images/avatar-2.png';
import '../views/components/booking-card/images/services.svg';
import '../views/pages/room/images/main-image-room.jpg';
import '../views/pages/room/images/second-image-room.jpg';
import '../views/pages/room/images/third-image-room.jpg';
import '../views/pages/search-room/images/filter-icon.svg';
import '../views/components/footer/images/facebook.svg';
import '../views/components/footer/images/instagram.svg';
import '../views/components/footer/images/twitter.svg';
